pipeline {
    agent any

    stages {
        stage('start test') {
            steps {
                sh 'whoami'
                sh 'pwd'
            }
        }

        stage('docker build') {
            steps {
//                 sh 'docker build -t baekgu/baekgu_repo:back_dev ./backend/.'
                sh 'docker build -t baekgu-spring:0.0.1 ./backend/.'
            }
        }

        stage('docker deploy') {
            steps {
//                 sh 'docker rm -f backend_springboot && docker run -d baekgu-mysql:mysql -e MYSQL_ROOT_PASSWORD=0000 --link baekgu-redis:redis -p 9999:9999 --name backend_springboot gmkim716/baekgu_repo:docker'
//                 sh 'docker rm -f backend_springboot && docker run --name backend_springboot --link baekgu-mysql:mysql --link baekgu-redis:redis -p 9999:9999 baekgu_repo:docker'
//                 sh 'docker rm -f backend_springboot && docker run -d -p 9999:9999 --network test_network --name backend_springboot gmkim716/baekgu_repo:docker'

//                 성공했었던..
                sh 'docker rm -f baekgu-spring-boot && docker run -d -p 9999:9999 --name baekgu-spring-boot baekgu-spring:0.0.1'

                // redis try
//                 sh 'docker rm -f back_dev && docker run -d -p 9999:9999 --name back_dev --link baekgu-redis:redis baekgu-spring:0.0.1'
            }
        }
    }
}